### PR TITLE
Self Messages Update to Work w/ Vencord

### PR DESCRIPTION
**Pull request by its-x3non**
I updated the "SelfMessages" addon to work with Vencord (w/ ThemeAttributes Plugin on).
I also made a personal version of it to work with (possibly) any theme.
- I made the personal version first before I modified it for Virtual Boy. I made it a [CSS snippet](https://github.com/its-x3non/DiscordSnippets/tree/main/CSS%20Addons/Right%20Align%20Self%20Messages).

Here's a screenshot of it working w/ Vencord:
image

### CODE REVIEW

**Comment by Saltssaumure** [comment]
Why have you edited it so that it *does not* work with the selfmessages plugin anymore? Adding compatibility is cool, deleting existing compatibility is weird.

**Comment by its-x3non** [comment]
> Why have you edited it so that it *does not* work with the selfmessages plugin anymore? Adding compatibility is cool, deleting existing compatibility is weird.

I wasn't sure how to do both unless I could have kept `.selfmessages` for BD. I can add the snippet to my [existing repo](https://github.com/its-x3non/DiscordSnippets/blob/main/CSS%20Addons/Right%20Align%20Self%20Messages/Virtual%20Boy%20Compatability/RightAlignVB.css) for it to be its own import.  
I only use Vencord so I specifically made it for Vencord. I'm a bit new to this and I've only been making stuff for like a week now, my apologies.

**Comment by its-x3non** [comment]
I can't really test it out, but I don't seem to have any issues on Vencord when I add `.selfmessages`
My apologies again

**Comment by GH0STP4WZ** [comment]
Oh, I forgot to mention, Active development has been moved to [`Nexus-Themes/Virtual-Boy`](https://github.com/Nexus-Themes/Virtual-Boy). Which means that if I merge this, I will have to manually pull the changes to that repo. (as its not recognized as a fork by github for some reason)

Other than the isssue @Saltssaumure already mentioned, it looks pretty much good to go. I'll see if this has any issues with the most up-to-date version on the other repo before merging though.

**Review by GH0STP4WZ — CHANGES_REQUESTED** [review]
I've added this to my backlog of things to do. As of right now, I cant merge this with the up-to-date version of the self-messages addon, which I have just mirrored into this repo. If you can, please adapt your edits to the new version. Otherwise I wont be able to make this work, as I don't have access to a computer to develop on right now.

**Comment by its-x3non** [comment]
The edits *should* be adapted, unless I missed anything or messed up anything.

**Comment by GH0STP4WZ** [comment]
Looks good to me now. Seeing a small issue with the BD side of things, still. On my work's PC which I can probably fix. Gonna merge this now.

**Pull request merged**
